---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    driver_config:
      network:
      - [private_network, ip: 33.33.33.10]
    run_list:
      - recipe[apt::default]
    attributes:
      l2tp-ipsec:
        public_interface: eth1

  - name: ubuntu-14.04
    driver_config:
      network:
      - [private_network, ip: 33.33.33.11]
    run_list:
      - recipe[apt::default]
    attributes:
      l2tp-ipsec:
        public_interface: eth1


suites:
  - name: l2tp-ipsec
    run_list:
      - recipe[debnetwork::default]
      - recipe[fake::default]
    attributes:
      monit:
        poll_period: 30
        poll_start_delay: 0
      l2tp-ipsec:
        users:
        - username: bob
          vpn_password: bobsecret
        - username: alice
          vpn_password: alicesecret
